name: .NET 6 Lambda Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check .NET 6 SDK version
      run: dotnet --version

    - name: Check AWS CLI version
      run: aws --version
