name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.x
        sudo apt-get install -y awscli
        dotnet restore

    - name: Package Lambda
      run: |
        cd FixxAPI
        dotnet lambda package --project-location FixxAPI.csproj --output-package FixxAPI.zip

    - name: Deploy to AWS
      uses: aws-actions/upload-to-s3@master
      with:
        args: FixxAPI.zip
        bucket-name: fixxbucket
        object-key: FixxAPI.zip
      env:
        AWS_REGION: us-east-2

    - name: Update Lambda function
      run: |
        aws lambda update-function-code \
          --function-name fixx-api-lambda \
          --s3-bucket fixxbucket \
          --s3-key FixxAPI.zip \
          --publish \
          --region us-east-2

    - name: Deploy API Gateway
      run: |
        aws apigateway put-rest-api \
          --region ${{ env.AWS_REGION }} \
          --rest-api-id qdw2azkax8 \
          --mode overwrite \
          --fail-on-warnings \
          --body file://api-gateway-body.json
