name: Deploy to AWS Lambda
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup .NET 6
      run: |
        echo "Installing .NET 6"
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y apt-transport-https
        sudo apt-get update
        sudo apt-get install -y dotnet-sdk-6.0
    - name: Build and package
      run: |
        dotnet build -c Release
        dotnet lambda package -c Release --framework net6.0 -o function.zip
    - name: Deploy to AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Update Lambda function
      run: |
        aws lambda update-function-code --function-name fixxapi --zip-file fileb://function.zip
    - name: Update API Gateway
      run: |
        aws apigateway update-rest-api --rest-api-id 1u05oijt7b --patch-operations op='replace',path='/minimumCompressionSize',value='2048'
