name: .NET 6 AWS Serverless Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create or update Ubuntu instance
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Create or update Lambda function
      run: aws lambda create-function --function-name fixxapi --runtime dotnet6.0 --role arn:aws:lambda:us-east-2:735745902141:function:fixxapi --handler FixxAPI::FixxAPI.LambdaEntryPoint::FunctionHandlerAsync --zip-file fileb://function.zip
    - name: Create or update API Gateway
      run: aws apigateway create-deployment --rest-api-id 1u05oijt7b --stage-name prod --description "Prod deployment"
    
