name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

env:
  AWS_REGION: us-east-2
  S3_BUCKET: fixxbucket
  LAMBDA_NAME: fixx-api-lambda
  REST_API_NAME: fixx-api-gateway
  REST_API_ID: qdw2azkax8

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Install dependencies
      run: |
        dotnet restore FixxAPI/FixxAPI.csproj

    - name: Build and package the application
      run: |
        dotnet publish FixxAPI/FixxAPI.csproj -c Release -o FixxAPI/bin/Release/net6.0/publish
        dotnet lambda package --project-location FixxAPI/FixxAPI.csproj --configuration Release --framework net6.0 --output-package FixxAPI.zip

    - name: Upload to S3
      uses: aws-actions/aws-cli@v1
      with:
        args: s3 cp FixxAPI.zip s3://${{ env.S3_BUCKET }}/${{ env.LAMBDA_NAME }}/FixxAPI.zip

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-cli@v1
      with:
        args: |
          aws lambda update-function-code
          --function-name ${{ env.LAMBDA_NAME }}
          --s3-bucket ${{ env.S3_BUCKET }}
          --s3-key ${{ env.LAMBDA_NAME }}/FixxAPI.zip
          --region ${{ env.AWS_REGION }}

    - name: Update API Gateway
      uses: aws-actions/aws-cli@v1
      with:
        args: |
          aws apigateway put-integration
          --rest-api-id ${{ env.REST_API_ID }}
          --resource-id oj5uu5
          --http-method ANY
          --type AWS_PROXY
          --integration-http-method POST
          --uri arn:aws:apigateway:${{ env.AWS_REGION }}:lambda:path/2015-03-31/functions/${{ env.LAMBDA_NAME }}/invocations
          --region ${{ env
